openapi: 3.0.3
info:
  title: Gamer Vault LTS
  version: 1.0.0
  description: API para autentificacion, productos,

servers:
  - url: https://mg3hk6z5q4.execute-api.us-east-1.amazonaws.com/dev/
  - url: http://localhost:5000/

paths:
  /auth/login:
    post:
      summary: login
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: jason
                password:
                  type: string
                  example: admin
      responses:
        '201':
          description: Login exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login exitoso
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Contraseña incorrecta o usuario no registrado

  /auth/register:
    post:
      summary: Register
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - birth_date
                - email
                - password_hash
              properties:
                username:
                  type: string
                  example: jason
                birth_date:
                  type: string
                  format: date
                  example: 2000-01-01
                email:
                  type: string
                  format: email
                  example: jason@example.com
                password_hash:
                  type: string
                  example: admin1234
      responses:
        '201':
          description: Registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Registered successfully
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: The username is already in use
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unexpected error occurred during registration

  /products/videogames:
    get:
      summary: Obtener productos de la categoría "videogames"
      tags: [Products]
      responses:
        '200':
          description: Lista de productos de videojuegos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '404':
          description: Categoría o productos no encontrados

  /products/{product_id}/:
    get:
      summary: Obtener producto por ID
      tags: [Products]
      parameters:
        - name: product_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalles del producto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado

  /products/coins:
    get:
      summary: Obtener productos de la categoría "coins"
      tags: [Products]
      responses:
        '200':
          description: Lista de monedas agrupadas por juego
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CoinGameItem'
        '404':
          description: Categoría o monedas no encontradas

  /products/coins/games-list:
    get:
      summary: Obtener lista de juegos que tienen monedas
      tags: [Products]
      responses:
        '200':
          description: Lista única de juegos con monedas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GameListItem'
        '404':
          description: Categoría no encontrada

  /products/coins/{videogame_name}:
    get:
      summary: Obtener monedas para un videojuego específico
      tags: [Products]
      parameters:
        - name: videogame_name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de monedas para el videojuego indicado
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '404':
          description: Monedas no encontradas

components:
  schemas:
    Product:
      type: object
      properties:
        product_id:
          type: string
        name:
          type: string
        description:
          type: object
        price:
          type: number
          format: float
        image_url:
          type: string
        created_at:
          type: string
          format: date-time
        id_category:
          type: string
        category_name:
          type: string

    # Category:
    #   type: object
    #   properties:
    #     category_id:
    #       type: string
    #     name:
    #       type: string
    #     description:
    #       type: object

    CoinGameItem:
      type: object
      properties:
        game_name:
          type: string
        product_id:
          type: string
        image_url:
          type: string
        category_name:
          type: string

    GameListItem:
      type: object
      properties:
        game:
          type: string
        image_url:
          type: string
